# Generated by Django 2.1.2 on 2019-01-26 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, unique=True)),
                ('category_expected', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category_spent', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('category_date', models.DateField()),
                ('category_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.People')),
            ],
        ),
    ]
