# Generated by Django 2.1.2 on 2019-01-26 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
