# Generated by Django 2.1.2 on 2019-01-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_location',
            field=models.CharField(default='Mississauga', max_length=200),
        ),
    ]
