# Generated by Django 2.1.2 on 2019-01-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='method_of_payment',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Cash/Debit', 'Cash/Debit'), ('Pay_off_CC', 'Pay_off_CC')], default='Cash/Debit', max_length=11),
        ),
    ]
